### PR TITLE
Create hand-input.html

### PR DESCRIPTION
**Pull request by fordacious**
Added hand input sample.

The sample tracks individual joints and the tips of index fingers to demonstrate interaction.

@cabanier

### CODE REVIEW

**Review by cabanier — COMMENTED** [review]
Did you verify that it doesn't break on Quest?

**Comment by fordacious** [comment]
Looking good!

**Comment by cabanier** [comment]
What do you mean by "wrong orientation"? Does the scene not match your actual hands on quest?

**Comment by fordacious** [comment]
The model that is added to the scene by the input profile rendering library is oriented incorrectly and does not match the hands orientation. It is also not articulated.

https://lafordgithubtesting.github.io/webxr-samples/hands.html?usePolyfill=0

**Comment by cabanier** [comment]
I see. Yes, I think nobody is treating hands like a regular controller.
Maybe it's best to disable the hand model

**Comment by fordacious** [comment]
Do you mean just disabling the input profile models entirely? Or is there a way to specifically disable them for hands?

**Comment by cabanier** [comment]
just for hands. I don't know if it's possible with the input profile library.

**Comment by fordacious** [comment]
There is no code in this sample that specifically deals with the hand models so we'll probably just have to not use the input profile library in that case

**Comment by fordacious** [comment]
Done

**Comment by cabanier** [comment]
I didn't realize this is for the webxr-samples repo.
Do you want to replace `immersive-hands.html` with this file? Otherwise people won't be able to get to it from the landing page.

**Comment by fordacious** [comment]
Ah good point. I was going to add a new link as it is no longer a "proposal"

**Comment by cabanier** [comment]
We can that as a separate PR since we might want to discuss it first.

**Comment by fordacious** [comment]
SGTM

**Comment by fordacious** [comment]
@toji

**Comment by toji** [comment]
Comparing immersive-hands.html to this one, they both accomplish pretty much the same thing but I find the presentation of immersive-hands.html a little bit nicer (since it provides a scene rather than just a void) and I'd prefer to continue to support it since it's been part of the repo longer. (I was mildly surprised to see that the existing sample even supports AR sessions!) The only thing it really lacks is the interaction demonstration, which is pretty minimal.

So what I'd suggest is this:
 - Since hands are no longer a proposal, we can move immersive-hands.html out of the proposals folder and into the root directory/page.
 - That sample does have some outdated code paths in them, as a result of being added before the spec was finalized, so it would be nice to clean those out.
 - Maybe add a simple interactive element to the sample.

**Comment by fordacious** [comment]
A Hegelian synthesis SGTM. I'll make the change here.

**Comment by fordacious** [comment]
Updated. @cabanier  I just ran it on Quest and I noticed the local space origin is on the floor, which I believe is incorrect.

**Comment by cabanier** [comment]
Can I see it in immersive-hands.html?

**Comment by fordacious** [comment]
yup

**Comment by fordacious** [comment]
the old immersive-hands.html had an artificial offset of 1.5m. Removing that offset in this version makes it apparent.

**Comment by cabanier** [comment]
This is indeed a bug in the Oculus browser. I can't believe that this wasn't found before :-\
I will investigate this.

**Comment by fordacious** [comment]
@toji how is it looking?

**Comment by cabanier** [comment]
@fordacious feel free to pull this in. That way I can use it as a test case.
I fixed the bug on our end but it will need a thorough test cycle.

**Comment by toji** [comment]
Did some additional digging on the `local` space bug, because it was unfathomable to me that the `local` space was completely broken all this time.

Turns out that `local` is fine unless you have _either_ `local-floor` or `bounded-floor` in the session creation options `optionalFeatures` array. Most samples that use `local` space don't request those, which is why this bug doesn't usually show up. I imagine that when those features are requested the browser is passing something to the underlying API to say that the "native" space is floor-relative, and it's just not offsetting the `local` space properly.

For what it's worth I would typically say that those features should be removed from the session request because they're not used by this sample and I don't want developers to copy/paste unnecessary feature requests into their own code. I'm fine leaving it here as a testing case for Rik and co.

**Comment by toji** [comment]
Forgot to say in the previous comment: Thanks for merging this with the existing sample, and pushing it to the main page! And hey, finding bugs in the process is always a plus! :)

**Comment by cabanier** [comment]
Indeed. The code checked if those spaces were requested and then moved the origin to the floor.
I don't know why that was done as requesting support for the floor shouldn't shift the origin.

I have a fix but it won't be in the upcoming browser (=next week). It will likely ship 2-3  weeks from now.

**Comment by cabanier** [comment]
@fordacious we'll send you a free Quest if you find 2 more bugs :-)

**Comment by toji** [comment]
Hey, if free hardware is up for grabs do I get credit for discovering that WebXR is incompatible with desks? 😆

**Comment by cabanier** [comment]
> Hey, if free hardware is up for grabs do I get credit for discovering that WebXR is incompatible with desks? 😆

3 more bugs! :-)

**Pull request merged**
