### PR TITLE
Add spacewarp sample

### PR DESCRIPTION
**Pull request by dannysu**
Adding a sample page demonstrating the 'space-warp' feature for projection layers: https://immersive-web.github.io/layers/#spacewarp

### CODE REVIEW

**Comment by klausw** [comment]
@cabanier , can you take a look? I think having this sample looks useful, but I don't know how the `space-warp` feature is expected to be used.

**Comment by klausw** [comment]
@toji for the renderer changes

**Review by cabanier — COMMENTED** [review]
I think it's a bit too early to merge this as we may need to update the spec.
@dannysu , can you serve this from your repo for now?

**Comment by dannysu** [comment]
@cabanier Ah, ok. Ignore this please.

**Pull request closed without merging**
