### PR TITLE
Use the reference space reset transform if provided

### PR DESCRIPTION
**Pull request by cabanier**
Recenter the scene when there's a origin discontinuity.

### CODE REVIEW

**Comment by AdaRoseCannon** [comment]
This is to support unbounded reference spaces right?

**Comment by cabanier** [comment]
> This is to support unbounded reference spaces right?

No. I'm working on providing this transform attribute on the reset event. This would test that.

**Comment by AdaRoseCannon** [comment]
Ah I see! Well LGTM :)

**Comment by cabanier** [comment]
> Ah I see! Well LGTM :)

Thank you!

**Pull request merged**
